plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.11'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.openapi.generator' version '7.14.0'
}

group = 'com.temenos'
version = '0.0.1-SNAPSHOT'
description = 'Spring Boot reactive REST with logging setup'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}
openApiGenerate {
	generatorName = "spring"
	inputSpec = "$projectDir/src/main/resources/openapi/api.yaml"
	outputDir = "${project.layout.buildDirectory.get()}/generated-sources"
	apiPackage = "com.temenos.internship.assignment.api"
	modelPackage = "com.temenos.internship.assignment.model"
	configOptions = [
			reactive       : "true",
			interfaceOnly  : "true",
			useSpringBoot3 : "true",
			useTags        : "true",
			openApiNullable: "false"
	]
}

sourceSets {
	main {
		java {
			srcDir "${project.layout.buildDirectory.get()}/generated-sources/src/main/java"
		}
	}
}

compileJava.dependsOn tasks.openApiGenerate


dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
	implementation 'org.postgresql:r2dbc-postgresql'

	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'
	runtimeOnly 'org.postgresql:postgresql'

	implementation 'org.openapitools:jackson-databind-nullable:0.2.6'
	implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.8.6'
	implementation 'jakarta.validation:jakarta.validation-api'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

tasks.named('test') {
	useJUnitPlatform()
}
