spring.application.name=internship-assignment

server.port = 8082

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/assignment_db
spring.r2dbc.username=postgres
spring.r2dbc.password=orion

spring.flyway.url=jdbc:postgresql://localhost:5432/assignment_db
spring.flyway.user=postgres
spring.flyway.password=orion

spring.flyway.enabled=true
