spring.application.name=internship-assignment

server.port = 8082

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/assignment_db
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

spring.flyway.url=jdbc:postgresql://localhost:5432/assignment_db
spring.flyway.user=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}

spring.flyway.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
